### PR TITLE
Recover kernel argument names from llvm::Argument names for SPIR/SPIR-V

### LINKED ISSUE #2165: PoCL: `clGetKernelArgInfo(CL_KERNEL_ARG_NAME)` returns `CL_KERNEL_ARG_INFO_NOT_AVAILABLE` for SPIR-V binaries
Generated with Claude Code, Opus 4.7. I'll try to have it look at the code and see if it can fix the bug if it is alright with the project. 

[repro.zip](https://github.com/user-attachments/files/27164141/repro.zip)

edit: remove incorrect description wrt address space and type behavior.

## Summary

When a program is created from a SPIR-V binary via `clCreateProgramWithIL`
and built with `-cl-kernel-arg-info`, the OpenCL spec says
`clGetKernelArgInfo` should return the names, address qualifiers, etc.
of each kernel argument — provided the SPIR-V binary contains the
required `OpName` decorations.

PoCL (verified on both 6.0 and 7.2-pre) returns
`CL_KERNEL_ARG_INFO_NOT_AVAILABLE` specifically for `CL_KERNEL_ARG_NAME`.
The other queries — `CL_KERNEL_ARG_ADDRESS_QUALIFIER`,
`CL_KERNEL_ARG_TYPE_NAME`, `CL_KERNEL_ARG_TYPE_QUALIFIER`,
`CL_KERNEL_ARG_ACCESS_QUALIFIER` — all work correctly, because
`llvm-spirv -r` emits the corresponding LLVM IR metadata nodes
(`!kernel_arg_addr_space`, `!kernel_arg_type`, `!kernel_arg_type_qual`,
`!kernel_arg_access_qual`) that PoCL's metadata reader picks up.

This appears to affect all SPIR-V binaries created via
`clCreateProgramWithIL`, regardless of the front-end that produced them.
It is reproducible with stock clang's SPIR-V output — see
`kernel.cl` + `repro.c` in this directory.

For comparison, Intel NEO (`OpenCL 3.0 NEO`) returns the names
correctly from the same SPIR-V binary.

## Reproducer files

- `kernel.cl` — A trivial OpenCL C kernel with named arguments
- `repro.c` — Loads the SPIR-V, builds with `-cl-kernel-arg-info`,
  queries `clGetKernelArgInfo` for each arg, prints the result
- `Makefile` — Builds both, plus convenience targets

## Building

Requires:
- `clang` (any recent version with `-target spirv64` support; tested with clang 20)
- An OpenCL C development install with `cl.h` (`opencl-headers` on
  Debian/Ubuntu) and `libOpenCL` (`ocl-icd-libopencl1` on Debian/Ubuntu)
- `spirv-tools` for `spirv-dis` (the `inspect` target only)

```
$ make
clang -target spirv64 -cl-kernel-arg-info -c kernel.cl -o kernel.spv
cc -Wall -Wextra repro.c -lOpenCL -o repro
```

## Confirming the SPIR-V contains the names

```
$ make inspect
spirv-dis kernel.spv | grep -E 'OpName|OpFunctionParameter'
              OpName %__spirv_BuiltInGlobalInvocationId "__spirv_BuiltInGlobalInvocationId"
              OpName %arg_info_test "arg_info_test"
              OpName %data "data"
              OpName %data_len "data_len"
              OpName %scalar_a "scalar_a"
              OpName %scalar_b "scalar_b"
        %30 = OpFunctionParameter %_ptr_CrossWorkgroup_uint
        %31 = OpFunctionParameter %ulong
        %32 = OpFunctionParameter %uint
        %33 = OpFunctionParameter %uint
```

So the SPIR-V binary clearly carries one `OpName` per
`OpFunctionParameter`. Under the OpenCL SPIR-V Environment Specification,
this is the only requirement for `clGetKernelArgInfo` to surface the
names.

## Observed (PoCL)

```
$ make run-pocl-only
OCL_ICD_VENDORS=/tmp/pocl-only ./repro kernel.spv
Device:  cpu-skylake-avx512-Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (GenuineIntel)
Version: OpenCL 3.0 PoCL HSTR: cpu-x86_64-pc-linux-gnu-skylake-avx512
num_args: 4
arg 0: clGetKernelArgInfo(CL_KERNEL_ARG_NAME) -> CL_KERNEL_ARG_INFO_NOT_AVAILABLE
arg 1: clGetKernelArgInfo(CL_KERNEL_ARG_NAME) -> CL_KERNEL_ARG_INFO_NOT_AVAILABLE
arg 2: clGetKernelArgInfo(CL_KERNEL_ARG_NAME) -> CL_KERNEL_ARG_INFO_NOT_AVAILABLE
arg 3: clGetKernelArgInfo(CL_KERNEL_ARG_NAME) -> CL_KERNEL_ARG_INFO_NOT_AVAILABLE
```

## Expected (and observed on Intel NEO)

```
Device:  Intel(R) Iris(R) Plus Graphics
Version: OpenCL 3.0 NEO 
num_args: 4
arg 0: name="data"     address_qualifier=GLOBAL  (aq_err=CL_SUCCESS)
arg 1: name="data_len" address_qualifier=PRIVATE (aq_err=CL_SUCCESS)
arg 2: name="scalar_a" address_qualifier=PRIVATE (aq_err=CL_SUCCESS)
arg 3: name="scalar_b" address_qualifier=PRIVATE (aq_err=CL_SUCCESS)
```

## Versions tested

- PoCL 6.0 (Ubuntu/Debian package, libpocl 2.13.0)
- PoCL 7.2-pre (built from main as of 2026-04-28)
- clang 20.1.8 (front-end)
- Intel NEO 3.0 (control)

### PR DESCRIPTION
**Pull request by bricevideau-ai**
Fixes #2165.

## Summary

`clGetKernelArgInfo(CL_KERNEL_ARG_NAME)` returns `CL_KERNEL_ARG_INFO_NOT_AVAILABLE` for all SPIR/SPIR-V binaries on the CPU device, even when the SPIR-V binary contains correct `OpName` decorations and the program is built with `-cl-kernel-arg-info`. This affects both clang's own SPIR-V output (`-target spirv64 -cl-kernel-arg-info`) and SPIR-V from other front-ends (e.g. rust-gpu).

The fix walks `Kernel->args()` to recover names from the `llvm::Argument`s themselves, fulfilling the long-standing TODO at the original `else` branch ("Implement walking on the arguments themselves to get the names").

## Root cause

`pocl_get_kernel_arg_function_metadata` in `lib/CL/pocl_llvm_metadata.cc` reads kernel argument names from a `!kernel_arg_name` LLVM IR metadata node, written by clang when compiling OpenCL C with `-cl-kernel-arg-info`.

The SPIR-V LLVM translator (`llvm-spirv -r`) does **not** emit `!kernel_arg_name` even when the source SPIR-V binary contains `OpName` decorations on every `OpFunctionParameter`. It instead preserves the names directly on the `llvm::Argument`s of the kernel function, e.g.:

```
define spir_kernel void @arg_info_test(
    ptr addrspace(1) %data, i64 %data_len,
    i32 %scalar_a, i32 %scalar_b
) #0 !kernel_arg_addr_space !5 !kernel_arg_access_qual !6 ...
```

Note the `!kernel_arg_addr_space`/`!kernel_arg_access_qual`/`!kernel_arg_type`/`!kernel_arg_type_qual`/`!kernel_arg_base_type` MD nodes are present (and PoCL reads them correctly), but `!kernel_arg_name` is missing — so PoCL falls into the `else` branch and silently drops the names.

## Reproducer

```c
// k.cl
__kernel void arg_info_test(__global unsigned int *data,
                            unsigned long data_len,
                            unsigned int scalar_a,
                            unsigned int scalar_b) {
    if (get_global_id(0) == 0 && data_len >= 2) {
        data[0] = scalar_a;
        data[1] = scalar_b;
    }
}
```

```sh
clang -target spirv64 -cl-kernel-arg-info -c k.cl -o k.spv
spirv-dis k.spv | grep OpName
#                OpName %data "data"
#                OpName %data_len "data_len"
#                OpName %scalar_a "scalar_a"
#                OpName %scalar_b "scalar_b"
```

Then a host program loading `k.spv` via `clCreateProgramWithIL`, building with `-cl-kernel-arg-info`, and calling `clGetKernelArgInfo(... CL_KERNEL_ARG_NAME ...)` for each arg:

**Before this PR (PoCL 6.0 + 7.2-pre, Linux/CPU device):**
```
arg 0: clGetKernelArgInfo(CL_KERNEL_ARG_NAME) -> CL_KERNEL_ARG_INFO_NOT_AVAILABLE
arg 1: clGetKernelArgInfo(CL_KERNEL_ARG_NAME) -> CL_KERNEL_ARG_INFO_NOT_AVAILABLE
arg 2: clGetKernelArgInfo(CL_KERNEL_ARG_NAME) -> CL_KERNEL_ARG_INFO_NOT_AVAILABLE
arg 3: clGetKernelArgInfo(CL_KERNEL_ARG_NAME) -> CL_KERNEL_ARG_INFO_NOT_AVAILABLE
```

**After this PR (same binary, same build options):**
```
arg 0: name="data"     address_qualifier=GLOBAL
arg 1: name="data_len" address_qualifier=PRIVATE
arg 2: name="scalar_a" address_qualifier=PRIVATE
arg 3: name="scalar_b" address_qualifier=PRIVATE
```

(For comparison, Intel NEO returns the names correctly from the same binary without any patch.)

## Test plan

- [x] Existing PoCL test suite passes: 300/300 tests pass
- [x] PoCL kernel test subset: 101/101 tests pass
- [x] `CL_KERNEL_ARG_INFO_NOT_AVAILABLE` is still returned correctly when the binary legitimately strips arg names — only flips `POCL_HAS_KERNEL_ARG_NAME` when *every* arg has a name
- [x] Verified with stock clang SPIR-V output
- [x] Verified with rust-gpu SPIR-V output (different front-end, same root cause)

### CODE REVIEW

File: lib/CL/pocl_llvm_metadata.cc [hunk 1]
```diff
@@ -382,11 +382,35 @@ static int pocl_get_kernel_arg_function_metadata(llvm::Function *Kernel,
...
-    // With SPIR 2.0 generated by more modern (3.9) Clang there is no more
-    // "kernel_arg_name" metadata, so retrieve the name in another way
-    // \todo Implement walking on the arguments themselves to get the names
+    // Modern clang (>= 3.9) compiling OpenCL C, and the SPIR-V LLVM
+    // translator (`llvm-spirv -r`), drop the `!kernel_arg_name` metadata
+    // node and instead preserve the argument names directly on the
+    // `llvm::Argument`s of the kernel function. Recover them from there
+    // so reflection via `clGetKernelArgInfo(CL_KERNEL_ARG_NAME)` works
+    // for SPIR / SPIR-V binaries too.
+    bool all_named = true;
```
Comment (pjaaskel) [inline lib/CL/pocl_llvm_metadata.cc]: Can you pls use the LLVM style in the C++ file's variable naming?

```suggestion
    bool AllNamed = true;
```

Comment (Kerilk) [reply lib/CL/pocl_llvm_metadata.cc]: Thanks for the review, will address. I thought there was a clang format style file, but couldn't find it. Did I miss it?

Comment (pjaaskel) [reply lib/CL/pocl_llvm_metadata.cc]: Unfortunately clang format doesn't touch the variable names. We have an experimental clang-tidy script that would do it, but it's not yet upstreamed.

Comment (pjaaskel) [reply lib/CL/pocl_llvm_metadata.cc]: tools/scripts/format-{diff,branch}.sh invokes the clang-format to get the basic formatting done.

Comment (pjaaskel) [reply lib/CL/pocl_llvm_metadata.cc]: Otherwise, LGTM and is very useful patch. Perhaps add also a note to the next Changelog? Thanks!

**Review by franz — COMMENTED** [review]
LGTM (after style fixes)

**Comment by bricevideau-ai** [comment]
Thanks for the pointer to the format scripts and the LLVM-style preference. Pushed two follow-ups:

- 9456f3194 — renames the new locals to LLVM PascalCase
- 405173db6 — adds a 7.2 "Notable bugfixes" entry

Ran `tools/scripts/format-branch.sh` over the branch as a sanity check; no formatting changes flagged on top of the rename.

**Review by franz — APPROVED** [review]
