### PR TITLE
cbs: Fix hanging kernels with `unreachable`.

### LINKED ISSUE #1711: Regression: Kernel hangs after loopvec changes.
The following Julia/OpenCL kernel hangs when using the master branch of PoCL:

```julia
using OpenCL, pocl_jll, StaticArrays

cl.platform!("pocl")

function forloop(A)
    i = get_global_id()
    priv = MArray{Tuple{8}, Int}(undef)  # private array, backed by stack memory
    for j in 1:8
        k = mod1(j + i - 1, 8)
        A[k, 1] += @inbounds priv[j]
        barrier()
    end
end

function main()
    A = CLArray{Int}(undef, 8, 1)
    @device_code_native @opencl local_size=8 global_size=8 forloop(A)
    cl.finish(cl.queue())
end

main()
```

We compile this down to the following SPIR-V code, and execute it using the CPU back-end.

<details>

<summary>The SPIR-V code.</summary>

```
```spirv
; SPIR-V
; Version: 1.4
; Generator: Khronos LLVM/SPIR-V Translator; 14
; Bound: 131
; Schema: 0
               OpCapability Addresses
               OpCapability Linkage
               OpCapability Kernel
               OpCapability Int64
               OpCapability Int8
          %1 = OpExtInstImport "OpenCL.std"
               OpMemoryModel Physical64 OpenCL
               OpEntryPoint Kernel %127 "_Z7forloop13CLDeviceArrayI5Int64Li2ELi1EE" %30 %__spirv_BuiltInGlobalInvocationId
               OpSource OpenCL_C 200000
               OpName %__spirv_BuiltInGlobalInvocationId "__spirv_BuiltInGlobalInvocationId"
               OpName %julia__throw_boundserror_11608 "julia__throw_boundserror_11608"
               OpName %top "top"
               OpName %gpu_report_exception "gpu_report_exception"
               OpName %gpu_signal_exception "gpu_signal_exception"
               OpName %_Z7forloop13CLDeviceArrayI5Int64Li2ELi1EE "_Z7forloop13CLDeviceArrayI5Int64Li2ELi1EE"
               OpName %conversion "conversion"
               OpName %pass "pass"
               OpName %L48 "L48"
               OpName %L101 "L101"
               OpName %L121 "L121"
               OpName %value_phi "value_phi"
               OpName %_not4_not ".not4.not"
               OpName %_neg ".neg"
               OpName %_not ".not"
               OpName %_not2 ".not2"
               OpName %top_0 "top"
               OpName %top_1 "top"
               OpDecorate %30 Constant
               OpDecorate %30 Alignment 1
               OpDecorate %__spirv_BuiltInGlobalInvocationId LinkageAttributes "__spirv_BuiltInGlobalInvocationId" Import
               OpDecorate %__spirv_BuiltInGlobalInvocationId Constant
               OpDecorate %__spirv_BuiltInGlobalInvocationId BuiltIn GlobalInvocationId
               OpDecorate %_Z7forloop13CLDeviceArrayI5Int64Li2ELi1EE LinkageAttributes "_Z7forloop13CLDeviceArrayI5Int64Li2ELi1EE" Export
               OpDecorate %54 FuncParamAttr ByVal
               OpDecorate %63 Alignment 16
               OpDecorate %70 Alignment 8
               OpDecorate %79 Constant
               OpDecorate %94 NoSignedWrap
               OpDecorate %108 NoSignedWrap
               OpDecorate %108 NoUnsignedWrap
               OpDecorate %114 NoSignedWrap
               OpDecorate %118 NoSignedWrap
               OpDecorate %128 FuncParamAttr ByVal
      %uchar = OpTypeInt 8 0
      %ulong = OpTypeInt 64 0
       %uint = OpTypeInt 32 0
   %uchar_69 = OpConstant %uchar 69
   %uchar_82 = OpConstant %uchar 82
   %uchar_79 = OpConstant %uchar 79
   %uchar_58 = OpConstant %uchar 58
   %uchar_32 = OpConstant %uchar 32
  %uchar_117 = OpConstant %uchar 117
  %uchar_116 = OpConstant %uchar 116
   %uchar_45 = OpConstant %uchar 45
  %uchar_111 = OpConstant %uchar 111
  %uchar_102 = OpConstant %uchar 102
   %uchar_98 = OpConstant %uchar 98
  %uchar_110 = OpConstant %uchar 110
  %uchar_100 = OpConstant %uchar 100
  %uchar_115 = OpConstant %uchar 115
   %uchar_97 = OpConstant %uchar 97
  %uchar_114 = OpConstant %uchar 114
  %uchar_121 = OpConstant %uchar 121
   %uchar_99 = OpConstant %uchar 99
  %uchar_101 = OpConstant %uchar 101
   %uchar_46 = OpConstant %uchar 46
   %uchar_10 = OpConstant %uchar 10
    %uchar_0 = OpConstant %uchar 0
   %ulong_36 = OpConstant %ulong 36
    %ulong_2 = OpConstant %ulong 2
   %ulong_64 = OpConstant %ulong 64
    %ulong_0 = OpConstant %ulong 0
    %ulong_1 = OpConstant %ulong 1
     %uint_0 = OpConstant %uint 0
     %uint_3 = OpConstant %uint 3
%ulong_18446744073709551615 = OpConstant %ulong 18446744073709551615
     %uint_2 = OpConstant %uint 2
    %ulong_8 = OpConstant %ulong 8
    %ulong_3 = OpConstant %ulong 3
%_arr_uchar_ulong_36 = OpTypeArray %uchar %ulong_36
%_ptr_UniformConstant__arr_uchar_ulong_36 = OpTypePointer UniformConstant %_arr_uchar_ulong_36
    %v3ulong = OpTypeVector %ulong 3
%_ptr_Input_v3ulong = OpTypePointer Input %v3ulong
       %void = OpTypeVoid
         %35 = OpTypeFunction %void
%_ptr_UniformConstant_uchar = OpTypePointer UniformConstant %uchar
%_ptr_CrossWorkgroup_uchar = OpTypePointer CrossWorkgroup %uchar
%_arr_ulong_ulong_2 = OpTypeArray %ulong %ulong_2
 %_struct_47 = OpTypeStruct %_ptr_CrossWorkgroup_uchar %ulong %_arr_ulong_ulong_2 %ulong
 %_struct_46 = OpTypeStruct %_struct_47
%_ptr_Function__struct_46 = OpTypePointer Function %_struct_46
         %52 = OpTypeFunction %void %_ptr_Function__struct_46
%_arr_uchar_ulong_64 = OpTypeArray %uchar %ulong_64
%_ptr_Function__arr_uchar_ulong_64 = OpTypePointer Function %_arr_uchar_ulong_64
%_ptr_Function_uchar = OpTypePointer Function %uchar
%_arr_ulong_ulong_1 = OpTypeArray %ulong %ulong_1
%_ptr_Function__arr_ulong_ulong_1 = OpTypePointer Function %_arr_ulong_ulong_1
%_ptr_Function_ulong = OpTypePointer Function %ulong
%_ptr_UniformConstant__arr_uchar_ulong_64 = OpTypePointer UniformConstant %_arr_uchar_ulong_64
       %bool = OpTypeBool
%_ptr_Function__struct_47 = OpTypePointer Function %_struct_47
%_ptr_CrossWorkgroup_ulong = OpTypePointer CrossWorkgroup %ulong
%_ptr_Function__ptr_CrossWorkgroup_ulong = OpTypePointer Function %_ptr_CrossWorkgroup_ulong
         %28 = OpConstantComposite %_arr_uchar_ulong_36 %uchar_69 %uchar_82 %uchar_82 %uchar_79 %uchar_82 %uchar_58 %uchar_32 %uchar_79 %uchar_117 %uchar_116 %uchar_45 %uchar_111 %uchar_102 %uchar_45 %uchar_98 %uchar_111 %uchar_117 %uchar_110 %uchar_100 %uchar_115 %uchar_32 %uchar_97 %uchar_114 %uchar_114 %uchar_97 %uchar_121 %uchar_32 %uchar_97 %uchar_99 %uchar_99 %uchar_101 %uchar_115 %uchar_115 %uchar_46 %uchar_10 %uchar_0
         %30 = OpVariable %_ptr_UniformConstant__arr_uchar_ulong_36 UniformConstant %28
%__spirv_BuiltInGlobalInvocationId = OpVariable %_ptr_Input_v3ulong Input
         %77 = OpConstantNull %_arr_uchar_ulong_64
         %79 = OpVariable %_ptr_UniformConstant__arr_uchar_ulong_64 UniformConstant %77
%julia__throw_boundserror_11608 = OpFunction %void DontInline %35
        %top = OpLabel
         %39 = OpBitcast %_ptr_UniformConstant_uchar %30
         %41 = OpExtInst %uint %1 printf %39
         %43 = OpFunctionCall %void %gpu_report_exception
         %45 = OpFunctionCall %void %gpu_signal_exception
               OpUnreachable
               OpFunctionEnd
%gpu_report_exception = OpFunction %void None %35
      %top_0 = OpLabel
               OpReturn
               OpFunctionEnd
%gpu_signal_exception = OpFunction %void None %35
      %top_1 = OpLabel
               OpReturn
               OpFunctionEnd
%_Z7forloop13CLDeviceArrayI5Int64Li2ELi1EE = OpFunction %void None %52
         %54 = OpFunctionParameter %_ptr_Function__struct_46
 %conversion = OpLabel
         %63 = OpVariable %_ptr_Function__arr_uchar_ulong_64 Function
         %66 = OpInBoundsPtrAccessChain %_ptr_Function_uchar %63 %ulong_0 %ulong_0
         %70 = OpVariable %_ptr_Function__arr_ulong_ulong_1 Function
         %71 = OpLoad %v3ulong %__spirv_BuiltInGlobalInvocationId Aligned 32
         %72 = OpCompositeExtract %ulong %71 0
               OpLifetimeStart %66 64
         %76 = OpInBoundsPtrAccessChain %_ptr_Function_ulong %54 %ulong_0 %uint_0 %uint_3
         %80 = OpBitcast %_ptr_UniformConstant_uchar %79
               OpCopyMemorySized %66 %80 %ulong_64 Aligned 16
         %81 = OpLoad %ulong %76 Aligned 8
         %83 = OpSGreaterThan %bool %81 %ulong_0
         %84 = OpSelect %ulong %83 %81 %ulong_0
         %85 = OpBitcast %_ptr_Function_uchar %54
         %86 = OpBitcast %_ptr_Function_ulong %63
               OpBranch %pass
       %pass = OpLabel
  %value_phi = OpPhi %ulong %ulong_1 %conversion %108 %L101
        %110 = OpIAdd %ulong %value_phi %72
        %111 = OpSDiv %ulong %110 %ulong_8
        %112 = OpSLessThan %bool %110 %ulong_0
        %114 = OpShiftLeftLogical %ulong %111 %ulong_3
        %115 = OpINotEqual %bool %114 %110
        %116 = OpLogicalAnd %bool %112 %115
       %_neg = OpSelect %ulong %116 %ulong_18446744073709551615 %ulong_0
        %118 = OpIAdd %ulong %111 %_neg
        %119 = OpShiftLeftLogical %ulong %118 %ulong_3
        %120 = OpISub %ulong %110 %119
       %_not = OpIEqual %bool %110 %119
         %90 = OpSelect %ulong %_not %ulong_8 %120
        %101 = OpIAdd %ulong %90 %ulong_18446744073709551615
      %_not2 = OpULessThan %bool %101 %84
               OpBranchConditional %_not2 %L101 %L48
        %L48 = OpLabel
         %87 = OpInBoundsPtrAccessChain %_ptr_Function_ulong %70 %ulong_0 %ulong_0
         %89 = OpInBoundsPtrAccessChain %_ptr_Function__struct_47 %54 %ulong_0 %uint_0
               OpStore %87 %90 Aligned 8
               OpLifetimeStop %66 64
         %91 = OpFunctionCall %void %julia__throw_boundserror_11608
               OpUnreachable
       %L101 = OpLabel
         %94 = OpIAdd %ulong %value_phi %ulong_18446744073709551615
         %95 = OpInBoundsPtrAccessChain %_ptr_Function_ulong %86 %94
         %96 = OpLoad %ulong %95 Aligned 8
         %99 = OpBitcast %_ptr_Function__ptr_CrossWorkgroup_ulong %85
        %100 = OpLoad %_ptr_CrossWorkgroup_ulong %99 Aligned 8
        %102 = OpInBoundsPtrAccessChain %_ptr_CrossWorkgroup_ulong %100 %101
        %103 = OpLoad %ulong %102 Aligned 8
        %104 = OpIAdd %ulong %96 %103
               OpStore %102 %104 Aligned 8
               OpControlBarrier %uint_2 %uint_2 %uint_0
  %_not4_not = OpIEqual %bool %value_phi %ulong_8
        %108 = OpIAdd %ulong %value_phi %ulong_1
               OpBranchConditional %_not4_not %L121 %pass
       %L121 = OpLabel
               OpReturn
               OpFunctionEnd
        %127 = OpFunction %void None %52
        %128 = OpFunctionParameter %_ptr_Function__struct_46
        %129 = OpLabel
        %130 = OpFunctionCall %void %_Z7forloop13CLDeviceArrayI5Int64Li2ELi1EE %128
               OpReturn
               OpFunctionEnd
```

</details>

For convenience, I prepared a C reproducer, attached here along with the binary SPIR-V code: [wip.zip](https://github.com/user-attachments/files/18036632/wip.zip)

```
Using platform 0: Portable Computing Language
[2024-12-06 10:19:42.486758749] PoCL: in fn pocl_install_sigfpe_handler at line 265:
 |   GENERAL |  Installing SIGFPE handler...
[2024-12-06 10:19:42.517160613] PoCL: in fn POclGetDeviceInfo at line 70:
 |   GENERAL |  clGetDeviceInfo query of param 102b for cpu
Device: cpu-haswell-AMD Ryzen 9 5950X 16-Core Processor
[2024-12-06 10:19:42.517854024] PoCL: in fn POclCreateCommandQueue at line 104:
 |   GENERAL |  Created Command Queue 3 (0x5f8549b99330) on device 0
[2024-12-06 10:19:42.517878214] PoCL: in fn void pocl_llvm_create_context(cl_context) at line 589:
 |      LLVM |  Created context 2 (0x5f8549bcd9e0)
[2024-12-06 10:19:42.517883904] PoCL: in fn POclCreateContext at line 234:
 |   GENERAL |  Created Context 2 (0x5f8549bcd9e0)
[2024-12-06 10:19:42.517895124] PoCL: in fn POclRetainContext at line 32:
 | REFCOUNTS |  Retain Context 2 (0x5f8549bcd9e0), Refcount: 2
[2024-12-06 10:19:42.517901804] PoCL: in fn POclCreateCommandQueue at line 104:
 |   GENERAL |  Created Command Queue 4 (0x5f8549bbd9a0) on device 0
[2024-12-06 10:19:42.517915144] PoCL: in fn pocl_create_memobject at line 164:
 |    MEMORY |  CL_MEM_USE_HOST_PTR 0x5f8549bbdb00
[2024-12-06 10:19:42.517920823] PoCL: in fn pocl_create_memobject at line 217:
 |    MEMORY |  Trying driver allocation for CL_MEM_DEVICE_ADDRESS_EXT
[2024-12-06 10:19:42.517927423] PoCL: in fn pocl_driver_alloc_mem_obj at line 491:
 |    MEMORY |  Basic device ALLOC 0x5f8549bbdb00 / size 64
[2024-12-06 10:19:42.517934803] PoCL: in fn pocl_create_memobject at line 255:
 |    MEMORY |  Registered a CL_MEM_DEVICE_ADDRESS_EXT allocation with address '0x5f8549bbdb00'.
[2024-12-06 10:19:42.517942223] PoCL: in fn POclRetainContext at line 32:
 | REFCOUNTS |  Retain Context 2 (0x5f8549bcd9e0), Refcount: 3
[2024-12-06 10:19:42.517950163] PoCL: in fn POclCreateBuffer at line 341:
 |    MEMORY |  Created Buffer 5 (0x5f8549bbdb90), MEM_HOST_PTR: 0x5f8549bbdb00, device_ptrs[0]: 0x5f8549bbdb00, SIZE 64, FLAGS 3221225481
[2024-12-06 10:19:42.517957563] PoCL: in fn POclRetainContext at line 32:
 | REFCOUNTS |  Retain Context 2 (0x5f8549bcd9e0), Refcount: 4
[2024-12-06 10:19:42.517964383] PoCL: in fn POclSVMAlloc at line 141:
 |    MEMORY |  Allocated SVM: PTR 0x5f8549bbdb00, SIZE 64, FLAGS 1
[2024-12-06 10:19:42.518013422] PoCL: in fn POclRetainContext at line 32:
 | REFCOUNTS |  Retain Context 2 (0x5f8549bcd9e0), Refcount: 5
[2024-12-06 10:19:42.518053742] PoCL: in fn pocl_run_command_capture_output at line 1832:
 |   GENERAL |  Launching: /home/tim/.julia/artifacts/269dfd41c362fb61600d1b30682dd946a6ff0a5d/bin/llvm-spirv
[2024-12-06 10:19:42.524795339] PoCL: in fn compile_and_link_program at line 711:
 |      LLVM |  building program with options (null)
[2024-12-06 10:19:42.524809249] PoCL: in fn compile_and_link_program at line 748:
 |      LLVM |  building program for 1 devs with options (null)
[2024-12-06 10:19:42.524817608] PoCL: in fn compile_and_link_program at line 752:
 |      LLVM |     BUILDING for device: cpu
[2024-12-06 10:19:42.524847418] PoCL: in fn pocl_llvm_convert_and_link_ir at line 703:
 |      LLVM |  Found cached compiled SPIRV binary at /tmp/pocl/kcache/FE/CLBMAMBKJHOKMBPCIIAONMNBJEIIBNMCBNNDH/program.bc, skipping compilation
[2024-12-06 10:19:42.527132700] PoCL: in fn int pocl_get_kernel_arg_function_metadata(llvm::Function*, llvm::Module*, pocl_kernel_metadata_t*) at line 412:
 |   WARNING |  no name metadata for kernel args(this is normal when compiling from SPIR)
[2024-12-06 10:19:42.527150580] PoCL: in fn int pocl_llvm_get_kernels_metadata(cl_program, unsigned int) at line 573:
 |   WARNING |  Arg 0 () : Don't know how to determine type size
[2024-12-06 10:19:42.527167069] PoCL: in fn POclCreateKernel at line 135:
 |   GENERAL |  Created Kernel _Z7forloop13CLDeviceArrayI5Int64Li2ELi1EE (0x5f8549bacf10)
[2024-12-06 10:19:42.527173639] PoCL: in fn POclSetKernelArg at line 215:
 |   GENERAL |  Kernel _Z7forloop13CLDeviceArrayI5Int64Li2ELi1EE || SetArg idx   0 ||          || Local 0 || Size     40 || Value 0x7ffd629103b8 || Pointer (nil) || *(uint32*)Value:        0 || *(uint64*)Value:        0 ||
Hex Value:  00DBBB49 855F0000 40000000 00000000 08000000 00000000 01000000 00000000 08000000 00000000
Launching kernel
[2024-12-06 10:19:42.527185359] PoCL: in fn pocl_kernel_calc_wg_size at line 194:
 |   GENERAL |  Preparing kernel _Z7forloop13CLDeviceArrayI5Int64Li2ELi1EE with local size 8 x 1 x 1 group sizes 1 x 1 x 1...
[2024-12-06 10:19:42.527190549] PoCL: in fn POclRetainCommandQueue at line 35:
 | REFCOUNTS |  Retain Command Queue 4 (0x5f8549bbd9a0), Refcount: 2
[2024-12-06 10:19:42.527194949] PoCL: in fn pocl_create_event at line 471:
 |    EVENTS |  Created event 1 (0x5f8549bbed30) for Command ndrange_kernel
[2024-12-06 10:19:42.527200339] PoCL: in fn pocl_create_command_struct at line 640:
 |    EVENTS |  Created immediate command struct: CMD 0x5f8549bbec30 (event 1 / 0x5f8549bbed30, type: ndrange_kernel)
[2024-12-06 10:19:42.527205039] PoCL: in fn POclRetainKernel at line 33:
 | REFCOUNTS |  Retain Kernel _Z7forloop13CLDeviceArrayI5Int64Li2ELi1EE (0x5f8549bacf10), Refcount: 2
[2024-12-06 10:19:42.527209879] PoCL: in fn pocl_command_enqueue at line 1058:
 |    EVENTS |  In-order Q; adding event syncs
[2024-12-06 10:19:42.527214809] PoCL: in fn pocl_command_enqueue at line 1091:
 |    EVENTS |  Pushed Event 1 to CQ 4.
[2024-12-06 10:19:42.527220499] PoCL: in fn pocl_update_event_queued at line 1910:
 |    EVENTS |  Event queued: 1
[2024-12-06 10:19:42.527228429] PoCL: in fn pocl_update_event_submitted at line 1930:
 |    EVENTS |  Event submitted: 1
Waiting for completion
[2024-12-06 10:19:42.527322867] PoCL: in fn pocl_check_kernel_disk_cache at line 1009:
 |   GENERAL |  Using a cached WG function: /tmp/pocl/kcache/FE/CLBMAMBKJHOKMBPCIIAONMNBJEIIBNMCBNNDH/_Z7forloop13CLDeviceArrayI5Int64Li2ELi1EE/8-1-1-goffs0-smallgrid/_Z7forloop13CLDeviceArrayI5Int64Li2ELi1EE.so
[2024-12-06 10:19:42.527404066] PoCL: in fn pocl_update_event_running_unlocked at line 1949:
 |    EVENTS |  Event running: 1
```

... at which point the process hangs. Here, only one thread is actually executing, all the others are blocked in the PoCL work scheduler.

This does not occur on v6.0; I've bisected it to aaeb79666c191b46c5dd2d59f4389a45035addcc from https://github.com/pocl/pocl/pull/1552 (cc @pjaaskel). It reproduces across platforms.

<details>

<summary>Configuration log</summary>

```
-- The C compiler identification is GNU 14.2.1
-- The CXX compiler identification is GNU 14.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_SYSTEM_NAME: Linux
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- CMAKE_LIBRARY_ARCHITECTURE:
-- Performing Test HAVE_WARN_INCOMPATIBLE_POINTER_TYPES
-- Performing Test HAVE_WARN_INCOMPATIBLE_POINTER_TYPES - Success
-- Pocl source Git commit: aaeb79666c191b46c5dd2d59f4389a45035addcc
-- Pocl source Git branch: * (no branch, bisect started on 952bc559f)
  main
-- Pocl source Git describe: bisect/good-0dbf1c4492cb1e8de953441624790cb107baa1c3-1-gaaeb79666
-- Host CPU cores: 32
-- Found PkgConfig: /usr/bin/pkg-config (found version "2.3.0")
-- Checking for module 'hwloc>=1.0'
--   Found hwloc, version 2.11.2
-- Using hwloc (cached): 1
-- L1D Cacheline size detected: 64
-- Using llvm-config: /home/tim/.julia/artifacts/290d06a089f634a44dd3a8838acf3f08dbc77534/tools/llvm-config
-- LLVM binaries suffix :
-- llvm-config's LLVM_PREFIX is: /home/tim/Julia/depot/artifacts/290d06a089f634a44dd3a8838acf3f08dbc77534
-- llvm-config's LLVM_VERSION_FULL is: 16.0.6jl
-- LLVM_VERSION: 16.0
-- llvm-config's LLVM_CFLAGS is: -I/home/tim/Julia/depot/artifacts/290d06a089f634a44dd3a8838acf3f08dbc77534/include  -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- llvm-config's LLVM_CXXFLAGS is: -I/home/tim/Julia/depot/artifacts/290d06a089f634a44dd3a8838acf3f08dbc77534/include -std=c++17   -fno-exceptions -fno-rtti -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- llvm-config's LLVM_CPPFLAGS is: -I/home/tim/Julia/depot/artifacts/290d06a089f634a44dd3a8838acf3f08dbc77534/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- llvm-config's LLVM_LDFLAGS is: -L/home/tim/Julia/depot/artifacts/290d06a089f634a44dd3a8838acf3f08dbc77534/lib
-- llvm-config's LLVM_BINDIR is: /home/tim/Julia/depot/artifacts/290d06a089f634a44dd3a8838acf3f08dbc77534/tools
-- llvm-config's LLVM_LIBDIR is: /home/tim/Julia/depot/artifacts/290d06a089f634a44dd3a8838acf3f08dbc77534/lib
-- llvm-config's LLVM_INCLUDEDIR is: /home/tim/Julia/depot/artifacts/290d06a089f634a44dd3a8838acf3f08dbc77534/include
-- llvm-config's LLVM_ALL_TARGETS is: AMDGPU NVPTX WebAssembly BPF AVR X86
-- llvm-config's LLVM_HOST_TARGET is: x86_64-unknown-linux-gnu
-- llvm-config's LLVM_BUILD_MODE is: Release
-- llvm-config's LLVM_ASSERTS_BUILD is: OFF
-- llvm-config's LLVM_HAS_RTTI is: NO
-- llvm-config's LLVM_LIBS is: -lLLVM-16jl
-- llvm-config's LLVM_SYSLIBS is:
-- Found clang: /home/tim/Julia/depot/artifacts/290d06a089f634a44dd3a8838acf3f08dbc77534/tools/clang
-- Found clang++: /home/tim/Julia/depot/artifacts/290d06a089f634a44dd3a8838acf3f08dbc77534/tools/clang++
-- Found opt: /home/tim/Julia/depot/artifacts/290d06a089f634a44dd3a8838acf3f08dbc77534/tools/opt
-- Found llc: /home/tim/Julia/depot/artifacts/290d06a089f634a44dd3a8838acf3f08dbc77534/tools/llc
-- Found llvm-as: /home/tim/Julia/depot/artifacts/290d06a089f634a44dd3a8838acf3f08dbc77534/tools/llvm-as
-- Found llvm-link: /home/tim/Julia/depot/artifacts/290d06a089f634a44dd3a8838acf3f08dbc77534/tools/llvm-link
-- Found lli: /home/tim/Julia/depot/artifacts/290d06a089f634a44dd3a8838acf3f08dbc77534/tools/lli
-- Found llvm-spirv: /home/tim/.julia/artifacts/269dfd41c362fb61600d1b30682dd946a6ff0a5d/bin/llvm-spirv
-- Found spirv-link: /home/tim/.julia/artifacts/219e1b9a97ec75f861da593f90342137d6c34644/bin/spirv-link
-- udivmodti4 compiles without extra flags
-- Checking if LLVM is a DEBUG build
-- DEBUG build
-- Find out LLC target triple (for host x86_64-unknown-linux-gnu)
-- Find out LLC host CPU with /home/tim/Julia/depot/artifacts/290d06a089f634a44dd3a8838acf3f08dbc77534/tools/llc
-- Checking clang -march vs. -mcpu flag
--   Using -march=
-- Running LLVM link test
-- LLVM link test OK
-- Running Clang link test
-- Clang link test OK
-- Checking host support for _Float16 type
-- Looking for fork
-- Looking for fork - found
-- Looking for fsync
-- Looking for fsync - found
-- Looking for sleep
-- Looking for sleep - found
-- Looking for getrlimit
-- Looking for getrlimit - found
-- Looking for utime
-- Looking for utime - found
-- Looking for ANNOTATE_HAPPENS_BEFORE
-- Looking for ANNOTATE_HAPPENS_BEFORE - not found
-- Looking for futimens
-- Looking for futimens - found
-- Looking for posix_memalign
-- Looking for posix_memalign - found
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- Looking for fdatasync
-- Looking for fdatasync - found
-- Looking for mkdtemp
-- Looking for mkdtemp - found
-- Looking for mkstemps
-- Looking for mkstemps - found
-- Looking for vfork
-- Looking for vfork - found
-- Looking for mkostemps
-- Looking for mkostemps - found
-- Looking for dladdr
-- Looking for dladdr - found
-- Performing Test HAVE_64BIT_ATOMICS_WITHOUT_LIB
-- Performing Test HAVE_64BIT_ATOMICS_WITHOUT_LIB - Success
-- Private Datadir Relative path: ../share/pocl
-- Compiler supports IPO: YES
-- Enable Link-Time Optimization (IPO) while building pocl runtime : 1
-- Found Python3: /usr/bin/python3.12 (found version "3.12.7") found components: Interpreter
-- libdl found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Checking for module 'libxsmm-shared>=1.15'
--   Package 'libxsmm-shared' not found
-- Checking for module 'libxsmm-static>=1.15'
--   Package 'libxsmm-static' not found
-- libxsmm or libblas not found, disabled
-- Checking for module 'ocl-icd>=1.3'
--   Package 'ocl-icd' not found
-- ocl-icd not found -> trying fallback ICD implementations
-- Checking for module 'OpenCL>=1.2'
--   Found OpenCL, version 3.0
-- libOpenCL (unknown ICD loader) found
-- Using an ICD loader : 1
-- Run tests with ICD: 0
-- opencl.h not found or ICD disabled or ICD >= 3.0, using our headers
-- Host support for cl_khr_fp16 enabled
-- Failed to find tcecc or openasip-config, disabling TCE
-- TCE support : 0
-- Building the following device drivers: basic pthreads
-- Using generic OpenCL 2.0 atomics
-- sse2 SLEEF: 512bit vectors NOT available.
-- sse2 SLEEF: 256bit vectors NOT available.
-- sse2 SLEEF: 128bit vectors available.
-- sse2 SLEEF bc list: /home/tim/Julia/src/pocl/build/lib/kernel/host/sse2/c_sleefsp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/sse2/c_sleefdp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/sse2/c_sleef_glue_auto.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/sse2/v128_sleefsimdsp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/sse2/v128_sleefsimddp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/sse2/spir_wrapper_128bit.ll.bc
-- sse2 SLEEF bc: /home/tim/Julia/src/pocl/build/lib/kernel/host/sse2/sleef.bc
-- Host Kernel BC for "sse2": /home/tim/Julia/src/pocl/build/lib/kernel/host/kernel-x86_64-unknown-linux-gnu-sse2.bc
-- ssse3 SLEEF: 512bit vectors NOT available.
-- ssse3 SLEEF: 256bit vectors NOT available.
-- ssse3 SLEEF: 128bit vectors available.
-- ssse3 SLEEF bc list: /home/tim/Julia/src/pocl/build/lib/kernel/host/ssse3/c_sleefsp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/ssse3/c_sleefdp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/ssse3/c_sleef_glue_auto.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/ssse3/v128_sleefsimdsp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/ssse3/v128_sleefsimddp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/ssse3/spir_wrapper_128bit.ll.bc
-- ssse3 SLEEF bc: /home/tim/Julia/src/pocl/build/lib/kernel/host/ssse3/sleef.bc
-- Host Kernel BC for "ssse3": /home/tim/Julia/src/pocl/build/lib/kernel/host/kernel-x86_64-unknown-linux-gnu-ssse3.bc
-- sse41 SLEEF: 512bit vectors NOT available.
-- sse41 SLEEF: 256bit vectors NOT available.
-- sse41 SLEEF: 128bit vectors available.
-- sse41 SLEEF bc list: /home/tim/Julia/src/pocl/build/lib/kernel/host/sse41/c_sleefsp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/sse41/c_sleefdp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/sse41/c_sleef_glue_auto.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/sse41/v128_sleefsimdsp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/sse41/v128_sleefsimddp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/sse41/spir_wrapper_128bit.ll.bc
-- sse41 SLEEF bc: /home/tim/Julia/src/pocl/build/lib/kernel/host/sse41/sleef.bc
-- Host Kernel BC for "sse41": /home/tim/Julia/src/pocl/build/lib/kernel/host/kernel-x86_64-unknown-linux-gnu-sse41.bc
-- avx SLEEF: 512bit vectors NOT available.
-- avx SLEEF: 256bit vectors available.
-- avx SLEEF: 128bit vectors available.
-- avx SLEEF bc list: /home/tim/Julia/src/pocl/build/lib/kernel/host/avx/c_sleefsp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx/c_sleefdp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx/c_sleef_glue_auto.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx/v256_sleefsimdsp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx/v256_sleefsimddp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx/v128_sleefsimdsp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx/v128_sleefsimddp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx/spir_wrapper_256bit.ll.bc
-- avx SLEEF bc: /home/tim/Julia/src/pocl/build/lib/kernel/host/avx/sleef.bc
-- Host Kernel BC for "avx": /home/tim/Julia/src/pocl/build/lib/kernel/host/kernel-x86_64-unknown-linux-gnu-avx.bc
-- avx_f16c SLEEF: 512bit vectors NOT available.
-- avx_f16c SLEEF: 256bit vectors available.
-- avx_f16c SLEEF: 128bit vectors available.
-- avx_f16c SLEEF bc list: /home/tim/Julia/src/pocl/build/lib/kernel/host/avx_f16c/c_sleefsp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx_f16c/c_sleefdp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx_f16c/c_sleef_glue_auto.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx_f16c/v256_sleefsimdsp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx_f16c/v256_sleefsimddp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx_f16c/v128_sleefsimdsp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx_f16c/v128_sleefsimddp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx_f16c/spir_wrapper_256bit.ll.bc
-- avx_f16c SLEEF bc: /home/tim/Julia/src/pocl/build/lib/kernel/host/avx_f16c/sleef.bc
-- Host Kernel BC for "avx_f16c": /home/tim/Julia/src/pocl/build/lib/kernel/host/kernel-x86_64-unknown-linux-gnu-avx_f16c.bc
-- avx_fma4 SLEEF: 512bit vectors NOT available.
-- avx_fma4 SLEEF: 256bit vectors available.
-- avx_fma4 SLEEF: 256bit hardware FMA available.
-- avx_fma4 SLEEF: 128bit vectors available.
-- avx_fma4 SLEEF: 128bit hardware FMA available.
-- avx_fma4 SLEEF bc list: /home/tim/Julia/src/pocl/build/lib/kernel/host/avx_fma4/c_sleefsp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx_fma4/c_sleefdp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx_fma4/c_sleef_glue_auto.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx_fma4/v256_sleefsimdsp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx_fma4/v256_sleefsimddp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx_fma4/v128_sleefsimdsp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx_fma4/v128_sleefsimddp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx_fma4/spir_wrapper_256bit.ll.bc
-- avx_fma4 SLEEF bc: /home/tim/Julia/src/pocl/build/lib/kernel/host/avx_fma4/sleef.bc
-- Host Kernel BC for "avx_fma4": /home/tim/Julia/src/pocl/build/lib/kernel/host/kernel-x86_64-unknown-linux-gnu-avx_fma4.bc
-- avx2 SLEEF: 512bit vectors NOT available.
-- avx2 SLEEF: 256bit vectors available.
-- avx2 SLEEF: 256bit hardware FMA available.
-- avx2 SLEEF: 128bit vectors available.
-- avx2 SLEEF: 128bit hardware FMA available.
-- avx2 SLEEF bc list: /home/tim/Julia/src/pocl/build/lib/kernel/host/avx2/c_sleefsp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx2/c_sleefdp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx2/c_sleef_glue_auto.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx2/v256_sleefsimdsp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx2/v256_sleefsimddp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx2/v128_sleefsimdsp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx2/v128_sleefsimddp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx2/spir_wrapper_256bit.ll.bc
-- avx2 SLEEF bc: /home/tim/Julia/src/pocl/build/lib/kernel/host/avx2/sleef.bc
-- Host Kernel BC for "avx2": /home/tim/Julia/src/pocl/build/lib/kernel/host/kernel-x86_64-unknown-linux-gnu-avx2.bc
-- avx512 SLEEF: 512bit vectors available.
-- avx512 SLEEF: 512bit hardware FMA available.
-- avx512 SLEEF: 256bit vectors available.
-- avx512 SLEEF: 256bit hardware FMA available.
-- avx512 SLEEF: 128bit vectors available.
-- avx512 SLEEF: 128bit hardware FMA available.
-- avx512 SLEEF bc list: /home/tim/Julia/src/pocl/build/lib/kernel/host/avx512/c_sleefsp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx512/c_sleefdp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx512/c_sleef_glue_auto.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx512/v512_sleefsimdsp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx512/v512_sleefsimddp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx512/v256_sleefsimdsp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx512/v256_sleefsimddp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx512/v128_sleefsimdsp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx512/v128_sleefsimddp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/avx512/spir_wrapper_512bit.ll.bc
-- avx512 SLEEF bc: /home/tim/Julia/src/pocl/build/lib/kernel/host/avx512/sleef.bc
-- Host Kernel BC for "avx512": /home/tim/Julia/src/pocl/build/lib/kernel/host/kernel-x86_64-unknown-linux-gnu-avx512.bc
-- generic SLEEF: 512bit vectors NOT available.
-- generic SLEEF: 256bit vectors NOT available.
-- generic SLEEF: 128bit vectors available.
-- generic SLEEF bc list: /home/tim/Julia/src/pocl/build/lib/kernel/host/generic/c_sleefsp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/generic/c_sleefdp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/generic/c_sleef_glue_auto.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/generic/v128_sleefsimdsp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/generic/v128_sleefsimddp.c.bc;/home/tim/Julia/src/pocl/build/lib/kernel/host/generic/spir_wrapper_128bit.ll.bc
-- generic SLEEF bc: /home/tim/Julia/src/pocl/build/lib/kernel/host/generic/sleef.bc
-- Host Kernel BC for "generic": /home/tim/Julia/src/pocl/build/lib/kernel/host/kernel-x86_64-unknown-linux-gnu-generic.bc
-- CPACK_DEBIAN_ICD_PACKAGE_DEPENDS
-- CPACK_DEBIAN_ICD_PACKAGE_NAME
-- CPACK_DEBIAN_ICD_PACKAGE_PROVIDES
-- CPACK_DEBIAN_ICD_PACKAGE_RECOMMENDS
-- CPACK_DEBIAN_LIB_PACKAGE_BREAKS
-- CPACK_DEBIAN_LIB_PACKAGE_DEPENDS
-- CPACK_DEBIAN_LIB_PACKAGE_NAME
-- CPACK_DEBIAN_LIB_PACKAGE_RECOMMENDS
-- CPACK_DEBIAN_LIB_PACKAGE_REPLACES
-- OPENCL_LIBS: Threads::Threads;OpenCL
-- OPENCL_CFLAGS:
-- OPENCL_LIBDIR: /home/tim/.julia/artifacts/98a96034f0c7be043f08b162828add4f1169813c/lib/pkgconfig/../../lib
-- OPENCL_LIBNAME: OpenCL
-- POCLU LINK OPTS: poclu;Threads::Threads;OpenCL;-lm
-- CPACK_DEBIAN_ICD_PACKAGE_DEPENDS
-- CPACK_DEBIAN_ICD_PACKAGE_NAME
-- CPACK_DEBIAN_ICD_PACKAGE_PROVIDES
-- CPACK_DEBIAN_ICD_PACKAGE_RECOMMENDS
-- CPACK_DEBIAN_LIB_PACKAGE_BREAKS
-- CPACK_DEBIAN_LIB_PACKAGE_DEPENDS
-- CPACK_DEBIAN_LIB_PACKAGE_NAME
-- CPACK_DEBIAN_LIB_PACKAGE_RECOMMENDS
-- CPACK_DEBIAN_LIB_PACKAGE_REPLACES
-- CPACK_DEBIAN_POCLCC_PACKAGE_DEPENDS
-- CPACK_DEBIAN_POCLCC_PACKAGE_NAME
--
-- *********************** SUMMARY ***************************
--
-- ******* Directories:
--
-- CMAKE_INSTALL_PREFIX: /home/tim/Julia/src/pocl/target
-- POCL_INSTALL_CMAKE_CONFIG_DIR: /home/tim/Julia/src/pocl/target/lib/pocl/cmake
-- POCL_INSTALL_ICD_VENDORDIR: /home/tim/Julia/src/pocl/target/etc/OpenCL/vendors
-- POCL_INSTALL_OPENCL_HEADER_DIR: /home/tim/Julia/src/pocl/target/include/CL
-- POCL_INSTALL_PKGCONFIG_DIR: /home/tim/Julia/src/pocl/target/lib/pkgconfig
-- POCL_INSTALL_PRIVATE_DATADIR: /home/tim/Julia/src/pocl/target/share/pocl
-- POCL_INSTALL_PRIVATE_HEADER_DIR: /home/tim/Julia/src/pocl/target/share/pocl/include
-- POCL_INSTALL_PRIVATE_LIBDIR: /home/tim/Julia/src/pocl/target/lib/pocl
-- POCL_INSTALL_PUBLIC_BINDIR: /home/tim/Julia/src/pocl/target/bin
-- POCL_INSTALL_PUBLIC_HEADER_DIR: /home/tim/Julia/src/pocl/target/include
-- POCL_INSTALL_PUBLIC_LIBDIR: /home/tim/Julia/src/pocl/target/lib
--
--
-- ******* LLVM Programs:
--
-- LLVM_CONFIG: /home/tim/.julia/artifacts/290d06a089f634a44dd3a8838acf3f08dbc77534/tools/llvm-config
-- LLVM_OPT: /home/tim/Julia/depot/artifacts/290d06a089f634a44dd3a8838acf3f08dbc77534/tools/opt
-- LLVM_LLC: /home/tim/Julia/depot/artifacts/290d06a089f634a44dd3a8838acf3f08dbc77534/tools/llc
-- LLVM_AS: /home/tim/Julia/depot/artifacts/290d06a089f634a44dd3a8838acf3f08dbc77534/tools/llvm-as
-- LLVM_LINK: /home/tim/Julia/depot/artifacts/290d06a089f634a44dd3a8838acf3f08dbc77534/tools/llvm-link
-- LLVM_LLI: /home/tim/Julia/depot/artifacts/290d06a089f634a44dd3a8838acf3f08dbc77534/tools/lli
-- LLVM_FILECHECK_BIN:
-- WITH_LLVM_CONFIG (User preferred llvm-config): /home/tim/.julia/artifacts/290d06a089f634a44dd3a8838acf3f08dbc77534/tools/llvm-config
--
-- ******* Various Flags:
--
-- HAVE_CLOCK_GETTIME: 1
-- HAVE_GLEW:
-- HAVE_LIBXSMM: 0
-- HOST_AS_FLAGS:
-- HOST_CLANG_FLAGS: --target=x86_64-unknown-linux-gnu -D_HAS_FLOAT16_TYPE
-- HOST_LD_FLAGS: -shared
-- HOST_LLC_FLAGS: -relocation-model=pic -mtriple=x86_64-unknown-linux-gnu
--
-- LIB_API_VERSION: 2
-- LIB_BUILD_VERSION: 2.14.0
-- ICD_LD_FLAGS: -Wl,-Bsymbolic
-- EXTRA_KERNEL_FLAGS:
-- EXTRA_KERNEL_CXX_FLAGS:
-- EXTRA_KERNEL_CL_FLAGS:
-- EXTRA_KERNEL_C_FLAGS:
-- final KERNEL_CXX_FLAGS: -xc++ -std=c++11 -fno-stack-protector -fPIC -fno-jump-tables
-- final KERNEL_CL_FLAGS: -xcl -fno-stack-protector -fPIC -fno-jump-tables
-- final KERNEL_C_FLAGS: -xc -std=c11 -D__CBUILD__ -fno-math-errno -fno-stack-protector -fPIC -fno-jump-tables
--
-- CLANG_HAS_64B_MATH: ON
-- CLANG_HAS_128B_MATH: ON
-- CLANG_NEEDS_RTLIB: OFF
-- LLVM_VERSION: 16.0
-- LLVM_LIB_IS_SHARED:
-- LLVM_HAS_RTTI: NO
-- LLVM_LIB_MODE: --link-shared
-- LLVM_ASSERTS_BUILD: OFF
-- LLVM_BUILD_MODE: Release
-- LLVM_CFLAGS: -I/home/tim/Julia/depot/artifacts/290d06a089f634a44dd3a8838acf3f08dbc77534/include  -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- LLVM_CXXFLAGS: -I/home/tim/Julia/depot/artifacts/290d06a089f634a44dd3a8838acf3f08dbc77534/include -std=c++17   -fno-exceptions -fno-rtti -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- LLVM_CPPFLAGS: -I/home/tim/Julia/depot/artifacts/290d06a089f634a44dd3a8838acf3f08dbc77534/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- LLVM_LDFLAGS: -L/home/tim/Julia/depot/artifacts/290d06a089f634a44dd3a8838acf3f08dbc77534/lib
-- LLVM_LIBDIR: /home/tim/Julia/depot/artifacts/290d06a089f634a44dd3a8838acf3f08dbc77534/lib
-- LLVM_INCLUDEDIR: /home/tim/Julia/depot/artifacts/290d06a089f634a44dd3a8838acf3f08dbc77534/include
-- LLVM_SRC_ROOT:
-- LLVM_OBJ_ROOT:
-- LLVM_INCLUDE_DIRS:
-- LLVM_ALL_TARGETS: AMDGPU NVPTX WebAssembly BPF AVR X86
-- LLVM_HOST_TARGET: x86_64-unknown-linux-gnu
-- CLANG_TARGET_OPTION: --target=
-- CLANG_MARCH_FLAG: -march=
-- LLC_TRIPLE: x86_64-unknown-linux-gnu
-- LLC_HOST_CPU_AUTO: znver3
-- LLC_HOST_CPU:
-- SELECTED_HOST_CPU: znver3
-- HOST_CPU_FORCED: 0
-- HOST_CPU_SUPPORTS_FLOAT16: 1
--
-- MAX_EXTENDED_ALIGNMENT: 128
-- OCL_KERNEL_TARGET: x86_64-unknown-linux-gnu
-- OCL_KERNEL_TARGET_CPU: znver3
-- HOST_DEVICE_ADDRESS_BITS: 64
-- HOST_CPU_ENABLE_CL_KHR_FP16: 1
--
-- ----------- -------------------------------- --------
-- llvm libs libpocl will be linked to (POCL_LLVM_LIBS):
-- /home/tim/Julia/depot/artifacts/290d06a089f634a44dd3a8838acf3f08dbc77534/lib/libLLVM-16jl.so
-- ----------- -------------------------------- --------
-- clang libs libpocl will be linked to (CLANG_LIBFILES):
-- /home/tim/Julia/depot/artifacts/290d06a089f634a44dd3a8838acf3f08dbc77534/lib/libclang-cpp.so
-- ----------- -------------------------------- --------
-- system libs libpocl will be linked to (LLVM_SYSLIBS):
--
-- ----------- -------------------------------- --------
-- ******* Enabled features:
--
-- DEVELOPER_MODE: OFF
-- ENABLE_CONFORMANCE: OFF
-- ENABLE_HWLOC: ON
-- RENAME_POCL: OFF
-- ENABLE_IPO: YES
-- ENABLE_ICD: 1
-- ENABLE_TCE: 0
-- ENABLE_TCEMC: 0
-- ENABLE_HSA: OFF
-- ENABLE_ALMAIF_DEVICE: OFF
-- ENABLE_CUDA: OFF
-- ENABLE_CUDNN: OFF
-- ENABLE_HOST_CPU_DEVICES: ON
-- ENABLE_VULKAN: OFF
-- ENABLE_ASAN (address sanitizer): OFF
-- ENABLE_LSAN (leak sanitizer): OFF
-- ENABLE_TSAN (thread sanitizer): OFF
-- ENABLE_UBSAN (UB sanitizer): OFF
-- ENABLE_LTTNG: OFF
-- ENABLE_POCL_BUILDING: ON
-- ENABLE_POCL_FLOAT_CONVERSION: OFF
-- ENABLE_RELOCATION: ON
-- ENABLE_PROXY_DEVICE: OFF
-- ENABLE_PROXY_DEVICE_INTEROP: OFF
-- ENABLE_REMOTE_SERVER: OFF
-- ENABLE_REMOTE_CLIENT: OFF
-- ENABLE_D2D_MIG:
-- ENABLE_RDMA: OFF
-- ENABLE_CL_GET_GL_CONTEXT:
-- ENABLE_OPENGL_INTEROP:
-- ENABLE_EGL_INTEROP:
-- ENABLE_SLEEF: ON
-- ENABLE_SPIRV: ON
-- ENABLE_VALGRIND: OFF
-- INSTALL_OPENCL_HEADERS (Install our headers): OFF
-- OCL_DRIVERS (Drivers built): basic pthreads
-- OCL_TARGETS (Targets built): host
-- ENABLE_LLVM: ON
-- POCL_ICD_ABSOLUTE_PATH: ON
-- POCL_ASSERTS_BUILD: 1
-- TESTS_USE_ICD: 0
-- Available testsuites: AMD;AMDSDK2.9;AMDSDK3.0;ASL;arrayfire;clBLAS;CLBlast;clFFT;chipStar;conformance;CloverLeaf;Halide;IntelSVM;intel-compute-samples;oneapi-samples;simple-sycl-samples;dpcpp-book-samples;opencl-book-samples;OpenCV;Parboil;piglit;PyOpenCL;Rodinia;shoc;VexCL;ViennaCL;Glow
-- Enabled testsuites:
-- Disabled testsuites: AMD;AMDSDK2.9;AMDSDK3.0;ASL;arrayfire;clBLAS;CLBlast;clFFT;chipStar;conformance;CloverLeaf;Halide;IntelSVM;intel-compute-samples;oneapi-samples;simple-sycl-samples;dpcpp-book-samples;opencl-book-samples;OpenCV;Parboil;piglit;PyOpenCL;Rodinia;shoc;VexCL;ViennaCL;Glow
-- Testsuites are built from git master: OFF
-- Enable internal doxygen documentation: OFF
-- Kernel caching: ON
-- Kernel library CPU variants: sse2;ssse3;sse41;avx;avx_f16c;avx_fma4;avx2;avx512;generic
-- Kernel library distro build: 1
-- Use pocl custom memory allocator: OFF
-- L1d cacheline size: 64
-- Configuring done (7.0s)
-- Generating done (0.2s)
-- Build files have been written to: /home/tim/Julia/src/pocl/build
```

</details>

### PR DESCRIPTION
**Pull request by fodinabor**
Until now, just the first exiting basic block was reused as kernel exit. However, kernels may contain `unreachable` as exits as well. We don't want that to be our final kernel exit, though, so create a new `ret void` BB as exit.

Fixes #1711 

Thanks for reporting and the reproducer @maleadt

### CODE REVIEW

File: tests/regression/test_issue_1711.c [hunk 1]
```diff
@@ -0,0 +1,149 @@
...
+    }
+    fseek(f, 0, SEEK_END);
+    size_t size = ftell(f);
+    fseek(f, 0, SEEK_SET);
+
+    unsigned char* binary = (unsigned char*)malloc(size);
+    fread(binary, 1, size, f);
+    fclose(f);
+
+    cl_program program = clCreateProgramWithIL(context, binary, size, &err);
```
Comment (pjaaskel) [inline tests/regression/test_issue_1711.c:103]: What happens with this test if SPIR-V support is not enabled in the build? Seems all CIs pass so perhaps all of them have it enabled or? Can we make the test conditional on SPIR-V support in the cmake file?

File: tests/regression/test_issue_1711.c [hunk 2]
```diff
@@ -0,0 +1,149 @@
+#include <stdio.h>
```
Comment (pjaaskel) [inline tests/regression/test_issue_1711.c:1]: Please add (c) and license text.

**Review by pjaaskel — CHANGES_REQUESTED** [review]

**Review by franz — APPROVED** [review]
LGTM

**Review by pjaaskel — APPROVED** [review]
Thanks!
