### PR TITLE
Fix #1887

### LINKED ISSUE #1887: Windows: no devices if home directory path contains certain characters
```
PS C:\dev\ws-pocl> clinfo -l
Platform #0: Portable Computing Language
Platform #1: NVIDIA CUDA
 `-- Device #0: NVIDIA GeForce RTX 4070 Laptop GPU
Platform #2: Intel(R) OpenCL Graphics
 `-- Device #0: Intel(R) Arc(TM) Graphics
PS C:\dev\ws-pocl> clinfo -d 0:0
  Platform Name                                   Portable Computing Language
PS C:\dev\ws-pocl> $env:POCL_DEBUG=1
PS C:\dev\ws-pocl> clinfo -d 0:0
[2025-04-14 12:55:52.-732827376] PoCL: in fn pocl_cache_init_topdir at line 620:  *** ERROR ***  |     ERROR |  Could not create top directory (C:\Users\Henry Linjamõki\AppData\Local\pocl) for cache.

Note: if you have proper rights to create that directory, and still get the error, then most likely pocl and the program you're trying to run are linked to different versions of libstdc++ library.
This is not a bug in pocl and there's nothing we can do to fix it - you need both pocl and your program to be compiled for your system. This is known to happen with Luxmark benchmark binaries downloaded from website; Luxmark installed from your linux distribution's packages should work.
[2025-04-14 12:55:52.-865301467] PoCL: in fn pocl_init_devices at line 667:  *** ERROR ***  |     ERROR | CL_DEVICE_NOT_FOUND Cache directory initialization failed  Platform Name                                   Portable Computing Language
PS C:\dev\ws-pocl>
```

Notice the path in the error message: the `C:\Users\Henry Linjamõki\AppData\Local\pocl` string has one character wrong - the `õ` should be `ä` character.

### PR DESCRIPTION
**Pull request by jbleonesio**
Use "pocl_get_string_option" to retrieve LOCALAPPDATA and TEMP environment variables under Windows.
Modified "getenv_helper" to convert values to UTF-8 under Windows.

### CODE REVIEW

**Comment by pjaaskel** [comment]
Thanks for your contribution. Please use the tools/scripts/clang-format-branch.sh to format the style.  

@franz @linehill if it looks OK, we might include the fix to 7.0.

**Comment by jbleonesio** [comment]
@pjaaskel I just updated the PR with the proper formatting.

**Comment by franz** [comment]
@pjaaskel looks OK to me

File: lib/CL/pocl_cache.c [hunk 1]
```diff
@@ -563,12 +563,12 @@ pocl_cache_init_topdir ()
       return CL_FAILED;
 
 #elif defined(_WIN32)
-      tmp_path = getenv ("TEMP");
+      tmp_path = pocl_get_string_option ("LOCALAPPDATA");
       if (!tmp_path) {
```
Comment (pjaaskel) [inline lib/CL/pocl_cache.c:567]: Yes, this is existing code, but if there are other changes to this PR, please move the curly bracket to the next line as in the GNU C style.

**Review by pjaaskel — APPROVED** [review]
@linehill please verify it fixes the problem for you(r last name) and if it looks good, go ahead and pull after the tests pass.

**Comment by pjaaskel** [comment]
The build error the CI found is valid @jbleonesio:

```
D:\a\pocl\pocl\lib\CL\pocl_cache.c(566): error C2198: 'const char *pocl_get_string_option(const char *,const char *)': too few arguments for call
D:\a\pocl\pocl\lib\CL\pocl_cache.c(568): error C2198: 'const char *pocl_get_string_option(const char *,const char *)': too few arguments for call
```

**Comment by linehill** [comment]
I fixed the build issue locally with:
```diff
diff --git a/lib/CL/pocl_cache.c b/lib/CL/pocl_cache.c
index 261a8e700..2d2f88ab1 100644
--- a/lib/CL/pocl_cache.c
+++ b/lib/CL/pocl_cache.c
@@ -563,9 +563,9 @@ pocl_cache_init_topdir ()
       return CL_FAILED;

 #elif defined(_WIN32)
-      tmp_path = pocl_get_string_option ("LOCALAPPDATA");
+      tmp_path = pocl_get_string_option ("LOCALAPPDATA", NULL);
       if (!tmp_path) {
-          tmp_path = pocl_get_string_option ("TEMP");
+       tmp_path = pocl_get_string_option ("TEMP", NULL);
       }
       if (tmp_path == NULL)
         return CL_FAILED;
```
However, the PR doesn't seem to work for me:
```
PS C:\dev\ws-pocl> clinfo -l
[2025-05-13 06:17:42.-858993460] PoCL: in fn pocl_cache_init_topdir at line 621:  *** ERROR ***  |     ERROR |  Could not create top directory (C:\Users\Henry Linjamõki\AppData\Local\pocl) for cache.

Note: if you have proper rights to create that directory, and still get the error, then most likely pocl and the program you're trying to run are linked to different versions of libstdc++ library.
This is not a bug in pocl and there's nothing we can do to fix it - you need both pocl and your program to be compiled for your system. This is known to happen with Luxmark benchmark binaries downloaded from website; Luxmark installed from your linux distribution's packages should work.
[2025-05-13 06:17:42.-858993460] PoCL: in fn pocl_init_devices at line 667:  *** ERROR ***  |     ERROR | CL_DEVICE_NOT_FOUND Cache directory initialization failedPlatform #0: Portable Computing Language
Platform #1: NVIDIA CUDA
 `-- Device #0: NVIDIA GeForce RTX 4070 Laptop GPU
Platform #2: Intel(R) OpenCL Graphics
 `-- Device #0: Intel(R) Arc(TM) Graphics
PS C:\dev\ws-pocl>
```
Notice the error message prints a path that should be `C:\Users\Henry Linjamäki\AppData\Local\pocl`. The `ä` character gets changed to `õ` somewhere.

**Comment by jbleonesio** [comment]
@linehill Thanks, I made this mistake when replicating the changes that I was testing locally.

I realize my patch won't fix the issue in case ENABLE_LLVM_PLATFORM_SUPPORT=false because it would then link against pocl_file_util.c instead of pocl_llvm_file_utils.cc.

**Comment by linehill** [comment]
> I realize my patch won't fix the issue in case ENABLE_LLVM_PLATFORM_SUPPORT=false because it would then link against pocl_file_util.c instead of pocl_llvm_file_utils.cc.

I have the `ENABLE_LLVM_PLATFORM_SUPPORT` set to ON (it's default on Windows) and I see the runtime error.

**Comment by pjaaskel** [comment]
Cool project, this Squey, I happy that OpenCL and PoCL is useful for this. How complex your kernels are?

**Comment by jbleonesio** [comment]
@pjaaskel Thanks! They are [fairly basic](https://gitlab.com/squey/squey/-/blob/main/src/libpvparallelview/src/opencl/bci_z24.cl) actually but PoCL is helping **a alot** to have them running with great performances both on CUDA and CPU backends (compared to naive approach to render lines)

**Comment by pjaaskel** [comment]
Do you mean you also use PoCL-CUDA on Windows or that you used CUDA's OpenCL?

**Comment by jbleonesio** [comment]
@franz You raised a good point but I just tested a console executable from Squey testsuite that is testing PortableCL and its properly working under "Henry Linjamäki" user

@linehill Would you mind testing with commit https://github.com/pocl/pocl/commit/a2e0199f794c8dfbcd92b775cd4f82ba05e816a9 to check if something changed between the latest version ?

image

**Comment by linehill** [comment]
I found the source of the problem on my end. The windows version of `getenv_helper` was not enabled until the following fix:
```diff
diff --git a/lib/CL/pocl_runtime_config.c b/lib/CL/pocl_runtime_config.c
index 5b39e647d..eabf5fca8 100644
--- a/lib/CL/pocl_runtime_config.c
+++ b/lib/CL/pocl_runtime_config.c
@@ -29,7 +29,7 @@
 #include <stdlib.h>
 #include <string.h>

-#ifdef __WIN32__
+#ifdef _WIN32

 #include <windows.h>

``` 
With the fix the `pocl_cache_init_topdir` error is gone.

**Comment by jbleonesio** [comment]
@linehill Nice! I just updated my patch with your modification.

**Review by linehill — APPROVED** [review]
LGTM
